import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Memorama",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              <li>
                <Link href="/formEdicionJuego">
                  Formulario de edicion de juego
                </Link>
              </li>
              <li>
                <Link href="/formIngreso">
                  Formulario de ingreso para alumnos
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
