services:
  web:
    build: .
    command: gunicorn hexagon.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    volumes:
      - static_volume:/src/app/static
      - media_volume:/src/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
