# Generated by Django 5.0.3 on 2024-03-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidas',
            name='profesorID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.profesores'),
        ),
    ]
