# Generated by Django 5.0.3 on 2024-03-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_partidas_profesorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpartidas',
            name='partidaID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.partidas'),
        ),
    ]
