# Generated by Django 5.0.3 on 2024-03-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_subpartidas_partidaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpartidas',
            name='partidaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.partidas'),
        ),
    ]
