# Generated by Django 5.0.3 on 2024-03-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_subpartidas_cartaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidas',
            name='nombre',
            field=models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=50),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
