# Generated by Django 5.0.3 on 2024-03-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_cartas_cartapar'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpartidas',
            name='numeroJugadores',
            field=models.IntegerField(default=1),
        ),
    ]
