# Generated by Django 5.0.3 on 2024-03-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_cartas_partidaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpartidas',
            name='cartasEnPartidaID',
        ),
        migrations.CreateModel(
            name='CartasEnSubPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('cartaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.cartas')),
                ('subpartidaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.subpartidas')),
            ],
        ),
        migrations.DeleteModel(
            name='CartasEnPartida',
        ),
    ]
