# Generated by Django 5.0.3 on 2024-03-27 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alumnos_partidaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='partidaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.partidas'),
        ),
    ]
